#!/bin/bash

clear

#if no args passed display usage info
if [ $# -eq 0 ]; then
  COLOR='\033[1;33m'
  NONE='\033[0m'

  echo -e "${COLOR}Analyzes audio volume information for given file${NONE}"
  echo
  echo "usage: ffm-analyze-volume input_file"
  echo "   ex: ffm-analyze-volume input.mp4"
  echo
  exit 1
fi

ffmpeg -i $1 -af volumedetect -f null /dev/null
