#!/bin/bash

clear

#if no args passed display usage info
if [ $# -eq 0 ]; then
  RED='\033[1;31m'
  NONE='\033[0m'

  echo -e "${RED}Trims video from start time to end time - without reencoding${NONE}"
  echo "usage: ffm-trim input_file start_time end_time output_file"
  echo
  echo "   ex: ffm-trim input.mp4 00:00:15.5 00:35:05 output.mp4"
  echo
  exit 1
fi

TIME1=$2
TIME2=$3

SEC1=`date +%s -d ${TIME1}`
SEC2=`date +%s -d ${TIME2}`

DIFFSEC=`expr ${SEC2} - ${SEC1}`

ffmpeg -ss $2 -i $1 -t ${DIFFSEC} -c copy $4

echo -------------------------------------------------------
echo Start ${TIME1}
echo Finish ${TIME2}
echo Duration ${DIFFSEC} seconds == `date +%H:%M:%S -ud @${DIFFSEC}`
ffp $4
