#!/bin/bash
  
TIME1=$2
TIME2=$3

SEC1=`date +%s -d ${TIME1}`
SEC2=`date +%s -d ${TIME2}`

DIFFSEC=`expr ${SEC2} - ${SEC1}`
  
ffmpeg -ss $2 -i "$1" -t ${DIFFSEC} -b:v 1500k -bufsize 1500k -ar 44100 -c:v h264_nvenc -s 1280x720 -vf "fps=fps=30" -b:a 128k "$4"
#ffmpeg -ss $2 -i "$1" -t ${DIFFSEC} -b:v 650k -bufsize 650k -ar 44100 -c:v h264_nvenc -s 1280x720 -vf "fps=fps=30" -b:a 128k "$4"

echo -------------------------------------------------------
echo Start ${TIME1}
echo Finish ${TIME2}
echo Duration ${DIFFSEC} seconds == `date +%H:%M:%S -ud @${DIFFSEC}`
ffp "$4"

