#!/bin/bash

while getopts i:o:s: flag
do
    case "${flag}" in
        i) in=${OPTARG};;
        o) out=${OPTARG};;
        s) sub=${OPTARG};;
    esac
done

ffmpeg -i "$in" -b:v 1500k -bufsize 1500k -ar 44100 -c:v h264_nvenc -s 1280x720 -vf "subtitles='$sub':force_style='FontName=CMG Sans Condensed,Fontsize=27,Alignment=5,MarginL=10,MarginV=12,Outline=0,Shadow=0,PrimaryColour=&HFFFFFF&', fps=fps=30" -b:a 128k "$out"

echo "in: $in";
echo "out: $out";
echo "sub: $sub";
