#!/bin/bash
 
while getopts i:o:s: flag
do
    case "${flag}" in
        i) in=${OPTARG};;
        o) out=${OPTARG};;
        s) sub=${OPTARG};;
    esac
done

ffmpeg -loop 1 -i Crosses.jpg -i "$in" -b:v 1500k -bufsize 1500k -ar 44100 -c:v h264_nvenc -s 1280x720 -b:a 128k -af -filter_complex "[1]scale=555:312[inner];[inner]format=yuva420p,geq=lum='p(X,Y)':a='if(gt(abs(W/2-X),W/2-15)*gt(abs(H/2-Y),H/2-15),if(lte(hypot(15-(W/2-abs(W/2-X)),15-(H/2-abs(H/2-Y))),15),255,0),255)'[inner];[0][inner]overlay=703:386:shortest=1[out]; [out]ass='$sub'; [out]fps=fps=30[out]" -map "[out]" -map 1:a -y "$out"

echo "in: $in";
echo "out: $out";
echo "sub: $sub";

