#!/bin/bash

TIME1=$2
TIME2=$3

SEC1=`date +%s -d ${TIME1}`
SEC2=`date +%s -d ${TIME2}`

DIFFSEC=`expr ${SEC2} - ${SEC1}`

ffmpeg -ss $2 -i $1 -t ${DIFFSEC} -c copy $4

echo -------------------------------------------------------
echo Start ${TIME1}
echo Finish ${TIME2}
echo Duration ${DIFFSEC} seconds == `date +%H:%M:%S -ud @${DIFFSEC}`
ffp $4
