#!/bin/bash

while getopts i:o:s: flag
do
    case "${flag}" in
        i) in=${OPTARG};;
        o) out=${OPTARG};;
        s) sub=${OPTARG};;
    esac
done

##ffmpeg -i $in -b:v 1500k -bufsize 1500k -ar 44100 -c:v h264_nvenc -s 1280x720 -vf "ass=$sub, fps=fps=30" -b:a 128k  $out

ffmpeg -i $in -b:v 1500k -bufsize 1500k -ar 44100 -c:v h264_nvenc -s 1280x720 -vf "ass=$sub, fps=fps=30, eq=brightness=0.15" -af "volume=5.2dB" -b:a 128k  $out

echo "in: $in";
echo "out: $out";
echo "sub: $sub";
ffp "$out"
